syntax = "proto3";

package dev.vishal.zanzibar.proto;

message ObjectRef {
    string object_type = 1; // "bucket" or "object"
    string object_id = 2; // "photos" or "photos/cat.jgp"
}

message UserRef {
    ObjectRef object = 1; // eg: "bucket:photos"
    string relation = 2; // eg: "reader"
}

message Principal {
    oneof kind {
        string user_id = 1; // "alice"
        UsersetRef userset = 2; // "bucket:photos#reader"
    }
}

message Tuple {
    ObjectRef object = 1 // left side
    string relation = 2; // relation on object
    Principal principal = 3; // right side (user or userset)
}

message Rewrite {
    enum OpType { THIS = 0; UNION = 1; TUPLE_TO_USERSET = 2;}
    OpType op = 1;
    repeated Rewrite children = 2; // for UNION
    string tuples_on = 3; // for TUPLE_TO_USERSET on THIS object to read
    string computed_userset_rel = 4; // relation to evaulate on referenced objects
}

message RelationDef { 
    string name = 1; 
    Rewrite rewrite = 2;
}

message TypeDefinition { 
    string type = 1; r
    repeated RelationDef relations = 2;
}

message Namespace {
    repeated TypeDefinition types = 1;
}

message LoadNamespaceRequest {
    Namespace ns = 1;
}

message LoadNamespaceResponse {}

message WriteRequest {
    repeated Tuple tuples = 1;
}

message WriteResponse {}

message DeleteRequest { 
    repeated Tuple tuples = 1; 
}

message DeleteResponse {}

message ReadRequest { 
    ObjectRef object = 1; 
    string relation = 2; 
}
message ReadResponse { 
    repeated Tuple tuples = 1; 
}

message CheckRequest {
    ObjectRef object = 1;
    string relation = 2;
    string user_id = 3;
    int32 max_depth = 4;
}

message CheckResponse {
    bool allowed = 1;
}

service Authz {
    rpc LoadNamespace(LoadNamespaceRequest) returns (LoadNamespaceResponse);
    rpc WriteTuples(WriteRequest) returns (WriteResponse);
    rpc DeleteTuples(DeleteRequest) returns (DeleteResponse);
    rpc ReadTuples(ReadRequest) returns (ReadResponse);
    rpc Check(CheckRequest) returns (CheckResponse);
}